#!/usr/bin/env bash
# reproduce.sh — re-run the measurement from scratch.
#
# ⚠️ This makes live model calls and costs nothing on a free-tier account, but
# it DOES require reachable providers. It cannot reproduce the frontier half of
# this study: no paid frontier model was callable from the original environment
# (see README, "measured vs. reported"). The frontier table in
# data/frontier-scores.json is regenerated by the extraction scripts instead.
#
# Usage:  bash scripts/reproduce.sh [reps] [concurrency]
set -euo pipefail
cd "$(dirname "$0")/.."

REPS="${1:-2}"
CONC="${2:-2}"
SUBJECT="opencode/space-bunny-free"
ANCHORS="nvidia/z-ai/glm-5.3-flash,meta/muse-spark-1.3"
STAMP="$(date -u +%Y%m%dT%H%M%SZ)"
OUT="reports/reproduce-$STAMP"

echo "Output: $OUT"
echo "NOTE: the harness runs each model in an isolated empty working directory"
echo "      with --pure --format json. Omitting those three flags injects the"
echo "      operator's workspace instructions into the measurement, which we"
echo "      measured: ~2x slower and ~12k extra prompt tokens."

mkdir -p "$OUT"

echo
echo "--- 1/3  subject, full 88-item bank, $REPS repetitions ---"
node harness/bin/run-bench.mjs --items harness/items.json \
  --models "$SUBJECT" --reps "$REPS" --concurrency "$CONC" \
  --timeout 240000 --out "$OUT/subject-88"

echo
echo "--- 2/3  anchors, 45-item stratified subset, 1 repetition ---"
node harness/bin/run-bench.mjs --items data/items-anchor-44.json \
  --models "$ANCHORS" --reps 1 --concurrency "$CONC" \
  --timeout 180000 --out "$OUT/anchors"

echo
echo "--- 3/3  audit (re-scores the raw log; makes no model calls) ---"
node harness/adjudicate.mjs "$OUT/subject-88"
node harness/adjudicate-anchors.mjs "$OUT/anchors"

echo
echo "--- frontier table (no model calls; re-derives the reported scores) ---"
echo "    node extract/c1/extract_epoch.mjs"
echo "    Requires network access to epoch.ai. The result is checked against"
echo "    data/frontier-scores.json; the Epoch dataset is CC BY 4.0 and requires"
echo "    crediting Epoch AI (see data/ATTRIBUTION.md)."

echo
echo "Done. Compare $OUT against reports/round1/ using the same method the audit used:"
echo "  node harness/stat-verify.mjs"
echo "A different number is not automatically a failure: the subject model's"
echo "served configuration is not pinned by this repository. What must reproduce"
echo "is the measured reproducibility floor (~7.4pp at 1 rep), and any gap"
echo "smaller than that floor is not a result."
